# Jekyll configuration file (https://jekyllrb.com/docs/configuration/)

# Serving, does not include hostname
baseurl: ""

# Site settings
name: Sandip Bhagat
description: "Dreaming for awesome life"
url: "http://sandipbgt.com"
icon: "/assets/img/m-icon-blue-on-white.png"
featured_image: "/img/home-bg.jpg"
theme_color: "#F57C00"
author:
  name: Sandip Bhagat
  email: "sandipbgt@gmail.com"
  uri: "https://twitter.com/sandipbgt"
  twitter: sandipbgt
  google_plus: 115724525062730752670
  github: sandipbgt
  keybase: sandipbgt
  #tumblr: sandipbgt
  linkedin: sandipbgt
  facebook: sandip02
  fb_id:  100000280885884
  street: "Vidhapith Path, Biratnagar - 13"
  locality: Biratnagar
  region: Morang
  country: Nepal
  postcode: 56613
disqus_shortname: sandipbgt
google_cse_id: ""

# Google Analytics
google_analytics_id: "UA-68086241-1"

# Site Build settings
repository: "sandipbgt/sandipbgt.github.io"
branch: master
encoding: "utf-8"
timezone: Asia/Kathmandu
locale: en_us
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10

# Front matter defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: "true"

gems:
  - jekyll-paginate

include: ["_pages"]
exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - Gruntfile.js
  - package.json
  - npm-debug.log
  - node_modules
  - vendor
  - bundle
  - ".bundle"
  - ".sass-cache"
  - src
